name: census_classification
channels:
  - default
  - conda-forge
dependencies:
  - python=3.8   # or 2.7
  - scikit-learn
  - dvc
  - pandas
  - numpy
  - pytest
  - jupyter
  - jupyterlab
  - fastapi
  - uvicorn